version: '3'

services:
  bot:
    build:
      context: .
    working_dir: '/bot'
    env_file:
      - ./.env
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
