TAGS = {
    1: 'Zelení',
    2: 'Švýcar. demokr.',
    3: 'Volný blok',
    4: 'SPD',
    5: 'ČSSD',
    6: 'Pravý blok',
    7: 'ANS',
    8: 'TSS',
    9: 'APB',
    10: 'PRAMENY',
    11: 'Levice',
    12: 'PŘÍSAHA',
    13: 'SPOLU',
    14: 'SENIOŘI',
    15: 'Nevolte Urza.cz',
    16: 'Monarchiste.cz',
    17: 'Piráti+STAN',
    18: 'KSČM',
    19: 'MZH',
    20: 'ANO',
    21: 'OtČe',
    22: 'Moravané'
}
